# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fC_yaasOaLsm_xw0ocf19kj4Qxv698kI
"""

import numpy as np
import scipy as sc

A = ([[2, -1, 3, -1, 11],
               [-1, -2, -1, -1, -4],
               [3, 3, 1, 3, -2],
               [-2, 2, -2, 2, 4]])
print("Matriks augmented")
print("A = ", A)

n = len(A)
m = np.zeros((n, n))
for i in range(0, n):
  for j in range(i+1, n):
    m[j][i] = A[j][i]/ A[i][i]
    s = m[j][i]
    for k in range (0, n+1):
      A[j][k] = A[j][k]- s * A[i][k]
print("\nMatriks Eselon Baris")
print("A")

X = np.zeros((n, 1))
X[n-1][0] = A[n-1][n] / A[n-1][n-1]
for i in range(n-2, -1, -1):
  s = 0
  for j in range(i+1, n):
    s = s + A[i][j] * X[j][0]
    X[i][0] = (A[i][n] -s)/A[i][i]

print("Solusi")
print(X)